from datetime import datetime
import helics as h
from dots_infrastructure.DataClasses import TimeStepInformation, EsdlId, HelicsCalculationInformation, PublicationDescription, SubscriptionDescription
from dots_infrastructure.HelicsFederateHelpers import HelicsSimulationExecutor
from esdl import EnergySystem

# This file is generated, DO NOT edit this file!

class PvInstallationCalculationServiceBase(HelicsSimulationExecutor):

    def __init__(self):
        super().__init__()

        
        # Calculation: predict_solar_power
        predict_solar_power_inputs = [
        
            SubscriptionDescription(esdl_type="EnvironmentalProfiles", 
                                    input_name="solar_irradiance", 
                                    input_unit="Wm2", 
                                    input_type=h.HelicsDataType.VECTOR),
        ]
        predict_solar_power_outputs = [
        
            PublicationDescription(global_flag=True, 
                                    esdl_type="PVInstallation",
                                    output_name="potential_active_power",
                                    output_unit="W", 
                                    data_type=h.HelicsDataType.VECTOR),
        ]
        predict_solar_power_information = HelicsCalculationInformation(
            time_period_in_seconds=900,
            offset=0, 
            uninterruptible=False, 
            wait_for_current_time_update=False, 
            terminate_on_error=True, 
            calculation_name="predict_solar_power", 
            inputs=predict_solar_power_inputs, 
            outputs=predict_solar_power_outputs, 
            calculation_function=self.predict_solar_power
        )
        self.add_calculation(predict_solar_power_information)
        # Calculation: current_pv_power_production
        current_pv_power_production_inputs = [
        
            SubscriptionDescription(esdl_type="EnvironmentalProfiles", 
                                    input_name="current_solar_irradiance", 
                                    input_unit="Wm2", 
                                    input_type=h.HelicsDataType.DOUBLE),
        ]
        current_pv_power_production_outputs = [
        
            PublicationDescription(global_flag=True, 
                                    esdl_type="PVInstallation",
                                    output_name="pv_active_power",
                                    output_unit="W", 
                                    data_type=h.HelicsDataType.DOUBLE),
        ]
        current_pv_power_production_information = HelicsCalculationInformation(
            time_period_in_seconds=900,
            offset=0, 
            uninterruptible=False, 
            wait_for_current_time_update=False, 
            terminate_on_error=True, 
            calculation_name="current_pv_power_production", 
            inputs=current_pv_power_production_inputs, 
            outputs=current_pv_power_production_outputs, 
            calculation_function=self.current_pv_power_production
        )
        self.add_calculation(current_pv_power_production_information)

    
    def predict_solar_power(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        pass
    
    def current_pv_power_production(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        pass
    